<a href="https://colab.research.google.com/github/leegw1211/begin-ml/blob/main/tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# tensorflow 입문하기
# https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ko

In [2]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [3]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

11490434/11490434 [==============================] - 0s 0us/step


In [4]:
# keras의 sequential모델은 가장 기본적인 모델이다.
# 여러 개의 레이어를 순차적으로 쌓아서 구성한다.
# 첫번째 layer에만 input shape을 지정해준다. 이후 layer들은 자동으로 연결된다.
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [5]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [6]:
# pred는 텐서(tensor) 객체이다.
# 텐서는 다차원 배열로, tensorflow에서 데이터를 표현하고 연산을 수행하는 데 사용된다
# numpy()메서드를 사용해서 텐서를 배열로 다룰 수 있다. (호환되도록 설계되어 있다)
pred = model(x_train[:1])
pred # 1행 10열의 2차원 배열

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.13333029, 0.07559424, 0.2182143 , 0.10576788, 0.08319917,
        0.10043005, 0.06747405, 0.03801482, 0.0983483 , 0.0796269 ]],
      dtype=float32)>

In [7]:
mypred = pred.numpy()
print(mypred)
print(np.sum(mypred[0])) # 마지막 layer의 활성화 함수가 softmax이므로 총 합은 1이다

[[0.13333029 0.07559424 0.2182143  0.10576788 0.08319917 0.10043005
  0.06747405 0.03801482 0.0983483  0.0796269 ]]
1.0


In [9]:
# logit은 확률을 나타내는 값이 아니라, 확률을 생성하는 함수의 입력으로 사용되는 값이다.
# softmax함수를 사용하여 다중 클래스 분류를 수행하는 경우, 모델의 출력은 확률 분포일 것이다.
# softmax함수를 거치기 전의 값을 그대로 손실 함수에 전달하려고 하면, from_logits=True로 설정해 줘야 한다
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy()
#loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], mypred).numpy()

2.2982938

In [10]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [11]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 4ms/step - loss: 0.2994 - accuracy: 0.9113
Epoch 2/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1427 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.1090 - accuracy: 0.9666
Epoch 4/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0872 - accuracy: 0.9738
Epoch 5/5
1875/1875 [==============================] - 7s 4ms/step - loss: 0.0749 - accuracy: 0.9762


In [12]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0718 - accuracy: 0.9774 - 636ms/epoch - 2ms/step


[0.07177814841270447, 0.977400004863739]

In [13]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08534358, 0.08534359, 0.08534406, 0.08538959, 0.08534358,
        0.08534362, 0.08534358, 0.23186105, 0.08534358, 0.08534367],
       [0.08533984, 0.08535876, 0.23192011, 0.08534212, 0.08533984,
        0.08533986, 0.08533984, 0.08533984, 0.08533984, 0.08533984],
       [0.08535164, 0.23173371, 0.08535638, 0.08535312, 0.08535495,
        0.08535188, 0.08535261, 0.08541604, 0.0853778 , 0.08535191],
       [0.23194669, 0.08533818, 0.085343  , 0.0853382 , 0.08533818,
        0.08533822, 0.08533851, 0.08534221, 0.08533818, 0.08533866],
       [0.08535133, 0.08535016, 0.0853524 , 0.08535016, 0.23175691,
        0.08535051, 0.08535095, 0.08535708, 0.08535055, 0.08542994]],
      dtype=float32)>