<a href="https://colab.research.google.com/github/leegw1211/begin-ml/blob/main/tensorflow_tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# tensorflow 입문하기
# https://www.tensorflow.org/tutorials/quickstart/beginner?hl=ko

In [15]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.15.0


In [16]:
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0

In [17]:
# keras의 sequential모델은 가장 기본적인 모델이다.
# 여러 개의 레이어를 순차적으로 쌓아서 구성한다.
# 첫번째 layer에만 input shape을 지정해준다. 이후 layer들은 자동으로 연결된다.
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10, activation='softmax')
])

In [18]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [31]:
# pred는 텐서(tensor) 객체이다.
# 텐서는 다차원 배열로, tensorflow에서 데이터를 표현하고 연산을 수행하는 데 사용된다
# numpy()메서드를 사용해서 텐서를 배열로 다룰 수 있다. (호환되도록 설계되어 있다)
pred = model(x_train[:1])
pred # 1행 10열의 2차원 배열

<tf.Tensor: shape=(1, 10), dtype=float32, numpy=
array([[0.1822737 , 0.07032003, 0.07481067, 0.11530907, 0.07448664,
        0.10825825, 0.0487538 , 0.15679963, 0.08957556, 0.07941269]],
      dtype=float32)>

In [33]:
mypred = pred.numpy()
print(mypred)
print(np.sum(mypred[0])) # 마지막 layer의 활성화 함수가 softmax이므로 총 합은 1이다

[[0.1822737  0.07032003 0.07481067 0.11530907 0.07448664 0.10825825
  0.0487538  0.15679963 0.08957556 0.07941269]]
1.0


In [40]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], mypred).numpy()

2.295117

In [41]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

In [43]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 10s 5ms/step - loss: 0.0653 - accuracy: 0.9790
Epoch 2/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0580 - accuracy: 0.9815
Epoch 3/5
1875/1875 [==============================] - 8s 4ms/step - loss: 0.0538 - accuracy: 0.9828
Epoch 4/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0468 - accuracy: 0.9846
Epoch 5/5
1875/1875 [==============================] - 9s 5ms/step - loss: 0.0443 - accuracy: 0.9853


In [44]:
model.evaluate(x_test, y_test, verbose=2)

/usr/local/lib/python3.10/dist-packages/keras/src/backend.py:5727: UserWarning: "`sparse_categorical_crossentropy` received `from_logits=True`, but the `output` argument was produced by a Softmax activation and thus does not represent logits. Was this intended?
  output, from_logits = _get_logits(


313/313 - 1s - loss: 0.0750 - accuracy: 0.9790 - 882ms/epoch - 3ms/step


[0.07503161579370499, 0.9789999723434448]

In [45]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[0.08533678, 0.08533678, 0.0853368 , 0.08533699, 0.08533678,
        0.08533678, 0.08533678, 0.23196878, 0.08533678, 0.08533678],
       [0.08533692, 0.08533807, 0.23196661, 0.08533694, 0.08533692,
        0.08533692, 0.08533692, 0.08533692, 0.08533692, 0.08533692],
       [0.08537316, 0.23139213, 0.08537508, 0.08537319, 0.08537766,
        0.08537323, 0.08537412, 0.08560891, 0.08537933, 0.08537316],
       [0.2319692 , 0.08533675, 0.08533676, 0.08533675, 0.08533675,
        0.08533676, 0.08533675, 0.0853368 , 0.08533675, 0.08533677],
       [0.0853401 , 0.0853401 , 0.08534011, 0.0853401 , 0.23191622,
        0.0853401 , 0.0853401 , 0.08534113, 0.0853401 , 0.08536194]],
      dtype=float32)>